apiVersion: apps/v1
kind: Deployment
metadata:
  name: secureflow
  namespace: secureflow
  labels:
    app.kubernetes.io/name: secureflow
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: secureflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secureflow
    spec:
      serviceAccountName: secureflow
      automountServiceAccountToken: false
      enableServiceLinks: false
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: ghcr.io/simplyy-shadin/secureflow-devsecops:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: sqlite:////data/secureflow.db
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secureflow-runtime
                  key: jwt-secret-key
            - name: JWT_ISSUER
              value: secureflow
            - name: JWT_AUDIENCE
              value: secureflow-api
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "15"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: secureflow-data
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
