apiVersion: v1
kind: Service
metadata:
  name: secureflow
  namespace: secureflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secureflow
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
